# Generated by Django 3.2.10 on 2021-12-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('country_province', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('country', models.TextField()),
                ('details', models.TextField()),
            ],
        ),
    ]
